name: Build Spring Boot API

on:
  push:
    paths:
      - 'api/**'
    branches: [ "main" ]
  pull_request:
    paths:
    - 'api/**'
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Set up MySQL
      run: |
        sudo /etc/init.d/mysql start
        mysql -e 'CREATE DATABASE poppy;' -uroot -proot
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    
    - name: Build with Maven
      run: mvn -B package --file api/pom.xml
      env: 
        JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
