name: Build and test Spring Boot API

on:
  push:
    paths:
      - 'api/**'
    branches: [ "main" ]
  pull_request:
    paths:
    - 'api/**'
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-test:
    name: Build and test
    runs-on: ubuntu-latest
    environment: PRODUCTION
    
    steps:
    - name: Access secrets and variables
      run: |
        echo "Current environment: $ENVIRONMENT"
        echo "Secret value: ${{ secrets.DB_USERNAME }}"
        echo "Variable value: ${{ vars.DB_HOST }}"
    
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Set up MySQL
      run: |
        sudo /etc/init.d/mysql start
        mysql -e 'CREATE DATABASE poppy;' -uroot -proot
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'
        
    - name: Clean and validate Maven project
      run: mvn clean validate --file api/pom.xml

    - name: Run Unit tests
      run: echo "Hello, here we're!" # mvn test --file api/pom.xml
    
    - name: Build with Maven
      run: mvn -B package --file api/pom.xml -DskipTests
      env: 
        DB_HOST: ${{ vars.DB_HOST }}
        DB_PORT: ${{ vars.DB_PORT }}
        DB_NAME: ${{ vars.DB_NAME }}
        DB_USERNAME: ${{ secrets.DB_USERNAME }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Login to Azure Container Registry
      uses: docker/login-action@v1
      with:
        registry: ${{ secrets.ACR_REGISTRY }}.azurecr.io
        username: ${{ secrets.AZURE_CLIENT_ID }}
        password: ${{ secrets.AZURE_CLIENT_SECRET }}
      
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: api/
        push: true
        tags: ${{ vars.ACR_REGISTRY }}.azurecr.io/poppyapi:latest-$(date +%Y%m%d%H%M%S)-${{ github.sha }}

