name: Build and test Spring Boot API

on:
  push:
    paths:
      - 'api/**'
    branches: [ "main" ]
  pull_request:
    paths:
    - 'api/**'
    branches: [ "main" ]

jobs:
  build-and-test:
    name: Build and test
    runs-on: ubuntu-latest
    
    steps:
    - name: Set environment variable
      run: echo "ENVIRONMENT=PRODUCTION" >> $GITHUB_ENV

    - name: Access secrets and variables
      run: |
        echo "Current environment: $ENVIRONMENT"
        echo "Secret value: ${{ secrets.DB_USERNAME }}"
        echo "Variable value: ${{ env.DB_HOST }}"
    
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Set up MySQL
      run: |
        sudo /etc/init.d/mysql start
        mysql -e 'CREATE DATABASE poppy;' -uroot -proot
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'
    
    - name: Build and test with Maven
      run: mvn -B package --file api/pom.xml
      env: 
        DB_HOST: ${{ env.DB_HOST }}
        DB_PORT: ${{ env.DB_PORT }}
        DB_NAME: ${{ env.DB_NAME }}
        DB_USERNAME: ${{ secrets.DB_USERNAME }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
